//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authentication.API.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceRoutesAPI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceRoutesAPI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Authentication.API.Resource.ResourceRoutesAPI", typeof(ResourceRoutesAPI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddAccount.
        /// </summary>
        public static string AddAccount {
            get {
                return ResourceManager.GetString("AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAccounts.
        /// </summary>
        public static string GetAccounts {
            get {
                return ResourceManager.GetString("GetAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAccountById/{id}.
        /// </summary>
        public static string GetAccountById {
            get {
                return ResourceManager.GetString("GetAccountById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateAccount/{id}.
        /// </summary>
        public static string UpdateAccount {
            get {
                return ResourceManager.GetString("UpdateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteAccount/{id}.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddAccountClaimAction.
        /// </summary>
        public static string AddAccountClaimAction {
            get {
                return ResourceManager.GetString("AddAccountClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddAction.
        /// </summary>
        public static string AddAction {
            get {
                return ResourceManager.GetString("AddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddClaim.
        /// </summary>
        public static string AddClaim {
            get {
                return ResourceManager.GetString("AddClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddClaimAction.
        /// </summary>
        public static string AddClaimAction {
            get {
                return ResourceManager.GetString("AddClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteAccountClaimAction/{id}.
        /// </summary>
        public static string DeleteAccountClaimAction {
            get {
                return ResourceManager.GetString("DeleteAccountClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteAction/{id}.
        /// </summary>
        public static string DeleteAction {
            get {
                return ResourceManager.GetString("DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteClaim/{id}.
        /// </summary>
        public static string DeleteClaim {
            get {
                return ResourceManager.GetString("DeleteClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteClaimAction/{id}.
        /// </summary>
        public static string DeleteClaimAction {
            get {
                return ResourceManager.GetString("DeleteClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateToken.
        /// </summary>
        public static string GenerateToken {
            get {
                return ResourceManager.GetString("GenerateToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAccountClaimActionById/{id}.
        /// </summary>
        public static string GetAccountClaimActionById {
            get {
                return ResourceManager.GetString("GetAccountClaimActionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAccountClaimActions.
        /// </summary>
        public static string GetAccountClaimActions {
            get {
                return ResourceManager.GetString("GetAccountClaimActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetActionById/{id}.
        /// </summary>
        public static string GetActionById {
            get {
                return ResourceManager.GetString("GetActionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetActions.
        /// </summary>
        public static string GetActions {
            get {
                return ResourceManager.GetString("GetActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetClaimActionById/{id}.
        /// </summary>
        public static string GetClaimActionById {
            get {
                return ResourceManager.GetString("GetClaimActionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetClaimActions.
        /// </summary>
        public static string GetClaimActions {
            get {
                return ResourceManager.GetString("GetClaimActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetClaimById/{id}.
        /// </summary>
        public static string GetClaimById {
            get {
                return ResourceManager.GetString("GetClaimById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetClaims.
        /// </summary>
        public static string GetClaims {
            get {
                return ResourceManager.GetString("GetClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateAccountClaimAction/{id}.
        /// </summary>
        public static string UpdateAccountClaimAction {
            get {
                return ResourceManager.GetString("UpdateAccountClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateAction/{id}.
        /// </summary>
        public static string UpdateAction {
            get {
                return ResourceManager.GetString("UpdateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateClaim/{id}.
        /// </summary>
        public static string UpdateClaim {
            get {
                return ResourceManager.GetString("UpdateClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateClaimAction/{id}.
        /// </summary>
        public static string UpdateClaimAction {
            get {
                return ResourceManager.GetString("UpdateClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetApplications.
        /// </summary>
        public static string GetApplications {
            get {
                return ResourceManager.GetString("GetApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetApplicationById/{id}.
        /// </summary>
        public static string GetApplicationById {
            get {
                return ResourceManager.GetString("GetApplicationById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddApplication.
        /// </summary>
        public static string AddApplication {
            get {
                return ResourceManager.GetString("AddApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateApplication.
        /// </summary>
        public static string UpdateApplication {
            get {
                return ResourceManager.GetString("UpdateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteApplication/{id}.
        /// </summary>
        public static string DeleteApplication {
            get {
                return ResourceManager.GetString("DeleteApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetApplicationClaims.
        /// </summary>
        public static string GetApplicationClaims {
            get {
                return ResourceManager.GetString("GetApplicationClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetApplicationClaimById/{id}.
        /// </summary>
        public static string GetApplicationClaimById {
            get {
                return ResourceManager.GetString("GetApplicationClaimById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetApplicationClaimsByApplicationId/{applicationId}.
        /// </summary>
        public static string GetApplicationClaimsByApplicationId {
            get {
                return ResourceManager.GetString("GetApplicationClaimsByApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddApplicationClaim.
        /// </summary>
        public static string AddApplicationClaim {
            get {
                return ResourceManager.GetString("AddApplicationClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateApplicationClaim.
        /// </summary>
        public static string UpdateApplicationClaim {
            get {
                return ResourceManager.GetString("UpdateApplicationClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteApplicationClaim/{id}.
        /// </summary>
        public static string DeleteApplicationClaim {
            get {
                return ResourceManager.GetString("DeleteApplicationClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProducts.
        /// </summary>
        public static string GetProducts {
            get {
                return ResourceManager.GetString("GetProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductById/{id}.
        /// </summary>
        public static string GetProductById {
            get {
                return ResourceManager.GetString("GetProductById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddProduct.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateProduct.
        /// </summary>
        public static string UpdateProduct {
            get {
                return ResourceManager.GetString("UpdateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteProduct/{id}.
        /// </summary>
        public static string DeleteProduct {
            get {
                return ResourceManager.GetString("DeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductVariants.
        /// </summary>
        public static string GetProductVariants {
            get {
                return ResourceManager.GetString("GetProductVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductVariantById/{id}.
        /// </summary>
        public static string GetProductVariantById {
            get {
                return ResourceManager.GetString("GetProductVariantById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductVariantsByProductId/{productId}.
        /// </summary>
        public static string GetProductVariantsByProductId {
            get {
                return ResourceManager.GetString("GetProductVariantsByProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddProductVariant.
        /// </summary>
        public static string AddProductVariant {
            get {
                return ResourceManager.GetString("AddProductVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateProductVariant.
        /// </summary>
        public static string UpdateProductVariant {
            get {
                return ResourceManager.GetString("UpdateProductVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteProductVariant/{id}.
        /// </summary>
        public static string DeleteProductVariant {
            get {
                return ResourceManager.GetString("DeleteProductVariant", resourceCulture);
            }
        }
    }
}
